version: '3'

services:
  voltdb-1:
    image: kjadeja/cluster:10
    ports:
        - "37080:8080"
        - "21212:21212"

    entrypoint:
        "./start-volt-cluster.sh"
        
  voltdb-2:
    image: kjadeja/cluster:10
    ports:
        - "38080:8080"
        - "31212:21212"
  
    entrypoint:
        "./start-volt-cluster.sh"
        
  voltdb-3:
    image: kjadeja/cluster:10
    ports:
        - "39080:8080"
        - "32212:21212"

    entrypoint:
        "./start-volt-cluster.sh"
